name: Run Tests
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: 
      - '*'
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # check for flaky tests
        repeat_tests: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup update

      - name: Run Tests
        run: |
          cargo build
          cargo test
