name: Run Tests
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4

      - name: Install Deps
        run: |
          sudo apt-get install -y make git iverilog yosys gtkwave

      - name: Install Rust
        run: |
          rustup update


      - name: Run Tests
        run: |
          cargo test
